# -*- coding: utf-8 -*-
"""model_hanna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t8Sic5AhTiewTHrK1EZo_--8jwC4RUeu
"""

def model (shape, classes):
    input = Input(shape)
    X = Conv2D(32, (5, 5))(input)
    X = Conv2D(32, (5, 5))(X)
    X = MaxPooling2D(pool_size=(2,2))(X)
    X = Dropout(0.25)(X)
    X = Conv2D(32, (3, 3))(X)
    X = Conv2D(32, (3, 3))(X)
    X = MaxPooling2D(pool_size=(2,2))(X)
    X = Dropout(0.25)(X)
    X = Flatten()(X)
    X = Dense(10, activation = "softmax")(X)
    model = Model(inputs=input,outputs=X, name ='mynet')
    return model
mymodel = model((28,28,1), 10)
mymodel.summary()
mymodel.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics=['accuracy'])
mymodel.fit(x=train_batch, epochs = 1, validation_data=val_batch)